output "application_container_registry_name" {
  value       = azurecaf_name.container_registry.result
  description = "The Container Registry name generated by the Azure Cloud Adoption Framework."
}

output "application_container_registry" {
  value       = azurerm_container_registry.container-registry
  description = "The Container Registry settings."
  sensitive = true
}