output "aisearch_name" {
  value       = azurerm_search_service.search.name
  description = "The application name generated by the Azure Cloud Adoption Framework."
}

output "aisearch_index" {
  value       = "gpt-${azurerm_search_service.search.name}"
  description = "The application name generated by the Azure Cloud Adoption Framework."
}

output "aisearch_primary_key" {
  value       = azurerm_search_service.search.primary_key
  description = "The AI Search primary key."
}

output "aisearch_url" {
  value       = "https://${azurerm_search_service.search.name}.search.windows.net"
  description = "The AI Search URL."
}