output "application_caf_name" {
  value       = azurecaf_name.containerapp.result
  description = "The application name generated by the Azure Cloud Adoption Framework."
}

output "application_caf_url" {
  value       = azurerm_container_app.containerapp.ingress[0].fqdn
  description = "The generated url for the container app."
}